spring.profiles.active: test
server:
  port: 8090
---
spring:
  profiles: develop
  jpa:
    show_sql: false
    database: h2
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;IGNORECASE=TRUE
    username: sa
    password:
    initialization-mode: always
---
spring:
  profiles: test
  jpa:
    show_sql: false
    database: H2
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;IGNORECASE=TRUE
    username: sa
    password:
    initialization-mode: never